namespace Autransoft.MockService.Lib.Enums
{
    ///<Summary>
    /// 
    ///</Summary>
    public enum Methods
    {
        ///<Summary>
        /// 
        ///</Summary>
        Get,
        ///<Summary>
        /// 
        ///</Summary>
        Post,
        ///<Summary>
        /// 
        ///</Summary>
        Put,
        ///<Summary>
        /// 
        ///</Summary>
        Delete,
        ///<Summary>
        /// 
        ///</Summary>
        Patch
    }
}